java:
    8home:  /Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home
spinfer:
    home:   /Users/anil.koyuncu/projects/richedit/spinfer/spinfer.native
    #home:   /Users/anil.koyuncu/projects/spinfer/spinfer.native
dataset:
#    home:   /Users/anil.koyuncu/projects/test/richedit-core/python/data/gumInputLinux/
    home:   /data/richedit-core/python/data/gumInputLinux/

coccinelle:
    home:   /Users/anil.koyuncu/projects/richedit/spinfer/statics
    #home:   /Users/anil.koyuncu/projects/spinfer/statics


fixminer:
#    datapath: /Users/anil.koyuncu/projects/test/richedit-core/python/data/
    datapath: /data/richedit-core/python/data/
