java:
    8home:  /Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home
spinfer:
    home:   /Users/anil.koyuncu/projects/spinfer/spinfer.native
dataset:
    home:   /Users/anil.koyuncu/projects/test/fixminer-data/patches/
    repo:   /Users/anil.koyuncu/projects/test/fixminer-data/datasets
#    home:   /data/fixminer-core/python/data/gumInputLinux/

coccinelle:
    home:   /Users/anil.koyuncu/projects/spinfer/statics

fixminer:
    datapath: /Users/anil.koyuncu/projects/test/fixminer-data/
    projectType : c
#    datapath: /data/fixminer-core/python/data/
