java:
    8home:  /Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home
spinfer:
    home:   /Users/anilkoyuncu/projects/richedit/spinfer/spinfer.native
    #home:   /Users/anil.koyuncu/projects/spinfer/spinfer.native
dataset:
#    home:   /Users/anil.koyuncu/projects/test/richedit-core/python/data/gumInputLinux/
    home:   /Users/anilkoyuncu/projects/richedit/richedit-core/python/data/gumInputLinux
#    home:   /data/richedit-core/python/data/gumInputLinux/
    repo:   /Users/anilkoyuncu/projects/datasets

coccinelle:
    home:   /Users/anilkoyuncu/projects/richedit/spinfer/statics
    #home:   /Users/anil.koyuncu/projects/spinfer/statics


fixminer:
#    datapath: /Users/anil.koyuncu/projects/test/richedit-core/python/data/
    datapath: /Users/anilkoyuncu/projects/richedit/richedit-data/
    projectType : c
#    datapath: /data/richedit-core/python/data/
